### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by mgrover1** [openradar/open-radar-data#13]
@kmuehlbauer - can we revert back to supporting Python 3.8? According to the Python PEPs, we have another year or so until we need to move onto 3.9 for the minimum supported version

https://endoflife.date/python

The Py-ART CI is failing this morning due to not being able to support 3.8

**Comment by mgrover1** [comment]
Nevemind @kmuehlbauer - I checked into it more, and it looks like we are nearing the end of support there, with the Xarray related merged PR

https://github.com/ARM-DOE/pyart/pull/1384

I am working on updating our CI accordingly. Closing!

**Comment by kmuehlbauer** [comment]
@mgrover1 Yes, I was following the tracks of xarray which also drop 3.8.
