### ISSUE TITLE
new dtree file in zarr format

### ISSUE THREAD

**Issue by aladinor** [openradar/open-radar-data#53]
Hi everyone, 

I want to add a new radar datatree file in Zarr format. It has multiple folders and subfolders. Should I add it as a compressed (bz, tar, ...) file? I ask this because in [#52], I noticed that every folder and subfolder within the Zarr file will create a new registry entry. Around 150 entries will be added to the `registry.txt` file.

Let me know your thoughts

**Comment by kmuehlbauer** [comment]
@aladinor Yes, please use a compressed representation. We already have some files gzipped, so maybe just use `gzip` (eg. `.tar.gz`)? We can use extract the folder before usage in CI using context manager.

**Comment by aladinor** [comment]
Closed with #54
